### ISSUE TITLE
Input clarification

### ISSUE THREAD

**Issue by danielgeiszler** [InfectionMedicineProteomics/BINN#27]
Can you please clarify what the input format is? Is the minimum input format protein names and a quant matrix? The example input is only a "Protein" columns, but the test_data.csv has quite a few other columns.

**Comment by ErikHartman** [comment]
Hey! The minimum input format to create a network is: 
1. A data file. This really just needs the input column, in our case "Protein".
2. The network-file. 
3. Alternatively, a translation between input and network, which in our case was UniProt IDs and Reactome IDs.

`test_data.csv` should not have been in the example. We have now replaced it with `test_qm.csv` which contains what you'd expect. Hopefully this clears it up.

**Comment by danielgeiszler** [comment]
Thanks! That clears it up immensely.
