### ISSUE TITLE
 Seeking Assistance with Reproducing Results in 'Interpreting biologically informed neural networks' Paper

### ISSUE THREAD

**Issue by 123nineh** [InfectionMedicineProteomics/BINN#39]
Dear Professor,
Sorry to disturb you.

When we reproduced the article BINN, we found that Figure 3 and Figure 4 (a, c) could not be reproduced successfully, and the important features we got could not match the conclusions drawn in your article. Would you like to provide some suggestions to solve the problems?

Best Regards.

**Comment by ErikHartman** [comment]
Hi!

What aspect of Fig. 3 did you have problems to re-create? Did you run BINN with the same parameters as in the paper, and on the same data (using all samples as background in SHAP)? There is some stochasticity in the detected features, but especially the top features (showcased) should be the same (see our new notebook on [robustness](https://infectionmedicineproteomics.github.io/BINN/robustness/)).

For Fig. 4 a and c. These are just clustermaps of the top identified proteins (created using [seaborn](https://seaborn.pydata.org/generated/seaborn.clustermap.html)). The proteins can be identified in the first layer of the BINN. 

Feel free to get back to me with more information about your pipeline and how I can help you further :)
