### ISSUE TITLE
Issue regarding creation of network

### ISSUE THREAD

**Issue by rayadheeraj** [InfectionMedicineProteomics/BINN#41]
TypeError                                 Traceback (most recent call last)
[<ipython-input-27-00a81ff44753>](https://localhost:8080/#) in <cell line: 1>()
----> 1 network = Network(input_data=input_data, pathways=pathways, mapping=translation, verbose=True)

TypeError: Network.__init__() got an unexpected keyword argument 'verbose'

**Comment by ErikHartman** [comment]
Remove `verbose=True`
